/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.PatientSensor.Test;
import Business.PatientSensor.TestDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class PatientSensorVitalSign extends javax.swing.JPanel {
JPanel userProcessContainer;
private Patient patient;
private Enterprise enterprise;
private TestDirectory testdir;
private UserAccount account;
private String time;
    /**
     * Creates new form DonorSensorVitalSign
     */
    public PatientSensorVitalSign(JPanel userProcessContainer,Enterprise enterprise,Patient patient,UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.patient=patient;
         this.account = account;
         Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        testdir=patient.getTestDir();
         RandomVitalSign();
    }

    public void RandomVitalSign()
    { Random rn = new Random();
        BloodPlatletsField.setText(String.valueOf(rn.nextFloat()*(140-70) + 70));
        BloodPressureText.setText(String.valueOf(rn.nextFloat()*(130-80) + 80));
        HemaglobinTextField.setText(String.valueOf(rn.nextFloat()*(120-70) + 70));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        OrgantypeComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        BloodGroupTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AntigenAComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        AntigenBComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        AntigenCComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        AntigenDB1ComboBox = new javax.swing.JComboBox();
        AntigenDQComboBox = new javax.swing.JComboBox();
        BloodPlatletsField = new javax.swing.JTextField();
        BloodPressureText = new javax.swing.JTextField();
        HemaglobinTextField = new javax.swing.JTextField();
        BodySizeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TimeStampText = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Marker DQ Antigen");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 252, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel16.setText("Patient Lab Test");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 6, -1, -1));

        jLabel17.setText("Organ Type");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 53, -1, -1));

        OrgantypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lungs", "Kindney", "Heart", "Liver", "Pancreas", " " }));
        add(OrgantypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 49, -1, -1));

        jLabel11.setText("Blood Group");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 83, -1, -1));

        BloodGroupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupTextFieldActionPerformed(evt);
            }
        });
        add(BloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 78, 110, -1));

        jLabel9.setText("Marker A Antigen");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, -1, -1));

        AntigenAComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        AntigenAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntigenAComboBoxActionPerformed(evt);
            }
        });
        add(AntigenAComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 120, 115, -1));

        jLabel8.setText("Marker B Antigen");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 148, -1, -1));

        AntigenBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        add(AntigenBComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 153, 115, -1));

        jLabel7.setText("Marker C Antigen");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 185, 168, -1));

        AntigenCComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        add(AntigenCComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 186, 115, -1));

        jLabel6.setText("Marker DB1 Antigen");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 207, -1, 25));

        AntigenDB1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        add(AntigenDB1ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 219, 115, -1));

        AntigenDQComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        AntigenDQComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntigenDQComboBoxActionPerformed(evt);
            }
        });
        add(AntigenDQComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 252, 109, -1));

        BloodPlatletsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPlatletsFieldActionPerformed(evt);
            }
        });
        add(BloodPlatletsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 291, 109, -1));
        add(BloodPressureText, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 329, 107, -1));
        add(HemaglobinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 367, 111, -1));
        add(BodySizeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 398, 107, -1));

        jLabel4.setText("Hemaglobin level");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 374, -1, -1));

        jLabel15.setText("Blood Pressure");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 332, -1, 20));

        jLabel3.setText("Blood Platlets");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 291, -1, -1));

        jLabel14.setText("Body Mass");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 408, -1, -1));

        jLabel2.setText("TimeStamp");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 441, -1, -1));
        add(TimeStampText, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 436, 107, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 498, -1, -1));

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 498, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AntigenAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntigenAComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntigenAComboBoxActionPerformed

    private void BloodPlatletsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPlatletsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPlatletsFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
//        request.setTestResult(ResultComboBox.getSelectedItem().toString());
//        request.setStatus("Completed");
//        request.setPatient(patient);
        Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        Test test=testdir.addTest();

        test.setAntigenA(Integer.parseInt(AntigenAComboBox.getSelectedItem().toString()));
        test.setAntigenB(Integer.parseInt(AntigenBComboBox.getSelectedItem().toString()));
        test.setAntigenC(Integer.parseInt(AntigenCComboBox.getSelectedItem().toString()));
        test.setAntigenDB1(Integer.parseInt(AntigenDB1ComboBox.getSelectedItem().toString()));
        test.setAntigenDQ(Integer.parseInt(AntigenDQComboBox.getSelectedItem().toString()));
        test.setBloodPlatlets(BloodPlatletsField.getText());
        test.setBloodPressure(BloodPressureText.getText());
        test.setBodyWeight(Integer.parseInt(BodySizeText.getText()));
        test.setHemoglobinLevel(HemaglobinTextField.getText());
        test.setBloodType(BloodGroupTextField.getText());
        test.setOrganType(OrgantypeComboBox.getSelectedItem().toString());
        test.setTimestamp(time);
        
        if(Float.parseFloat(HemaglobinTextField.getText()) < 125 ||Float.parseFloat(BloodPlatletsField.getText()) < 130 || Float.parseFloat(BloodPressureText.getText()) <80||Float.parseFloat(BloodPressureText.getText()) >150)
        {
            
         LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage("Ambulance Required");
         request.setStatus("Send");
        request.setPatient(patient);
        request.setSender(account);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;

                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
           // account.getWorkQueue().getWorkRequestList().add(request);
           JOptionPane.showMessageDialog(null, "Vital Sign dropped significantly ambulance on way!!", "Info", JOptionPane.INFORMATION_MESSAGE);

     }
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void BloodGroupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodGroupTextFieldActionPerformed

    private void AntigenDQComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntigenDQComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntigenDQComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AntigenAComboBox;
    private javax.swing.JComboBox AntigenBComboBox;
    private javax.swing.JComboBox AntigenCComboBox;
    private javax.swing.JComboBox AntigenDB1ComboBox;
    private javax.swing.JComboBox AntigenDQComboBox;
    private javax.swing.JTextField BloodGroupTextField;
    private javax.swing.JTextField BloodPlatletsField;
    private javax.swing.JTextField BloodPressureText;
    private javax.swing.JTextField BodySizeText;
    private javax.swing.JTextField HemaglobinTextField;
    private javax.swing.JComboBox OrgantypeComboBox;
    private javax.swing.JTextField TimeStampText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
