/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;


import Business.DonorSensor.VitalSignDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.PatientSensor.Test;
import Business.PatientSensor.TestDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
private UserAccount userAccount;
   LabTestWorkRequest request;
   private Patient patient;
   private Enterprise enterprise;
   private TestDirectory vitalSignHistory;
   String time;
    /**
     * Creates new form ProcessRequestJPanel
     */
    public ProcessRequestJPanel(JPanel userProcessContainer, LabTestWorkRequest request,Patient patient,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.patient=patient;
        this.enterprise= enterprise;
        this.userAccount=userAccount;
        this.vitalSignHistory=this.patient.getTestDir();
        Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BloodGroupTextField = new javax.swing.JTextField();
        BloodPlatletsField = new javax.swing.JTextField();
        BloodPressureText = new javax.swing.JTextField();
        BodySizeText = new javax.swing.JTextField();
        HemaglobinTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AntigenCComboBox = new javax.swing.JComboBox();
        AntigenDQComboBox = new javax.swing.JComboBox();
        AntigenDB1ComboBox = new javax.swing.JComboBox();
        AntigenAComboBox = new javax.swing.JComboBox();
        AntigenBComboBox = new javax.swing.JComboBox();
        OrgantypeComboBox = new javax.swing.JComboBox();
        ResultComboBox = new javax.swing.JComboBox();
        TimeStampText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 572, -1, -1));

        jLabel1.setText("Result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 486, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 572, -1, -1));

        jLabel3.setText("Blood Platlets");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 308, -1, -1));

        jLabel4.setText("Hemaglobin level");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 380, -1, -1));

        jLabel5.setText("Marker DQ Antigen");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 281, -1, -1));

        jLabel6.setText("Marker DB1 Antigen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 248, -1, 25));

        jLabel7.setText("Marker C Antigen");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 219, 168, -1));

        jLabel8.setText("Marker B Antigen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 182, -1, -1));

        jLabel9.setText("Marker A Antigen");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 149, -1, -1));

        jLabel11.setText("Blood Group");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 117, -1, -1));

        jLabel14.setText("Body Mass");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 414, -1, -1));

        jLabel15.setText("Blood Pressure");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 342, -1, 20));
        jPanel1.add(BloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 117, 111, 20));

        BloodPlatletsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPlatletsFieldActionPerformed(evt);
            }
        });
        jPanel1.add(BloodPlatletsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 309, 111, -1));
        jPanel1.add(BloodPressureText, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 341, 111, -1));
        jPanel1.add(BodySizeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 405, 111, -1));
        jPanel1.add(HemaglobinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 373, 111, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel16.setText("Patient Lab Test");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 18, -1, -1));

        jLabel17.setText("Organ Type");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 88, -1, -1));

        AntigenCComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel1.add(AntigenCComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 215, 111, -1));

        AntigenDQComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel1.add(AntigenDQComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 281, 111, -1));

        AntigenDB1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel1.add(AntigenDB1ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 248, 111, -1));

        AntigenAComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        AntigenAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntigenAComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AntigenAComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 149, 111, -1));

        AntigenBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel1.add(AntigenBComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 182, 111, -1));

        OrgantypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lungs", "Kindney", "Heart", "Liver", "Pancreas", " " }));
        jPanel1.add(OrgantypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 84, -1, -1));

        ResultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pending", "Complete" }));
        jPanel1.add(ResultComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 486, -1, -1));
        jPanel1.add(TimeStampText, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 443, 111, -1));

        jLabel2.setText("TimeStamp");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 448, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setTestResult(ResultComboBox.getSelectedItem().toString());
        request.setStatus("Completed");
        request.setPatient(patient);
        Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        Test test=vitalSignHistory.addTest();
        
        test.setAntigenA(Integer.parseInt(AntigenAComboBox.getSelectedItem().toString()));
        test.setAntigenB(Integer.parseInt(AntigenBComboBox.getSelectedItem().toString()));
        test.setAntigenC(Integer.parseInt(AntigenCComboBox.getSelectedItem().toString()));
        test.setAntigenDB1(Integer.parseInt(AntigenDB1ComboBox.getSelectedItem().toString()));
        test.setAntigenDQ(Integer.parseInt(AntigenDQComboBox.getSelectedItem().toString()));
        test.setBloodPlatlets(BloodPlatletsField.getText());
        test.setBloodPressure(BloodPressureText.getText());
        test.setBodyWeight(Integer.parseInt(BodySizeText.getText()));
       test.setHemoglobinLevel(HemaglobinTextField.getText());
        test.setBloodType(BloodGroupTextField.getText());
        test.setOrganType(OrgantypeComboBox.getSelectedItem().toString());
        test.setTimestamp(time);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PatientOrganization){
                org = organization;
                
                
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Patient added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
          
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkQueueJPanel dwjp = (NurseWorkQueueJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void BloodPlatletsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPlatletsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPlatletsFieldActionPerformed

    private void AntigenAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntigenAComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntigenAComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AntigenAComboBox;
    private javax.swing.JComboBox AntigenBComboBox;
    private javax.swing.JComboBox AntigenCComboBox;
    private javax.swing.JComboBox AntigenDB1ComboBox;
    private javax.swing.JComboBox AntigenDQComboBox;
    private javax.swing.JTextField BloodGroupTextField;
    private javax.swing.JTextField BloodPlatletsField;
    private javax.swing.JTextField BloodPressureText;
    private javax.swing.JTextField BodySizeText;
    private javax.swing.JTextField HemaglobinTextField;
    private javax.swing.JComboBox OrgantypeComboBox;
    private javax.swing.JComboBox ResultComboBox;
    private javax.swing.JTextField TimeStampText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
