/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmacyAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.OrganBank;
import static Business.Enterprise.Enterprise.EnterpriseType.Pharmacy;
import Business.Network.Network;
import Business.Order.OrderCatalog;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyAdminOrganization;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class PharmacyWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private Enterprise enterprise;
private PharmacyAdminOrganization Adminorganization;
private UserAccount account;
private EcoSystem system;
    
   // private SupplierDirectory supplierDirectory;
    
    
    /**
     * Creates new form PharmacyWorkAreaJPanel
     */
    public PharmacyWorkAreaJPanel(JPanel userProcessContainer,Organization organization,Enterprise enterprise,UserAccount account,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        //this.supplierDirectory=supplierDirectory;
        this.account=account;
        this.Adminorganization=(PharmacyAdminOrganization) organization;
        this.enterprise=enterprise;
        this.system= system;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageInventorybtn = new javax.swing.JButton();
        ManageSupplierbtn = new javax.swing.JButton();
        AddOrganizationBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 87, -1, -1));

        ManageInventorybtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageInventorybtn.setText("Manage Inventory >>");
        ManageInventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageInventorybtnActionPerformed(evt);
            }
        });
        add(ManageInventorybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 220, -1));

        ManageSupplierbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageSupplierbtn.setText("Manage Suppliers >>");
        ManageSupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupplierbtnActionPerformed(evt);
            }
        });
        add(ManageSupplierbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 220, -1));

        AddOrganizationBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        AddOrganizationBtn.setText("Add Organization>>");
        AddOrganizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrganizationBtnActionPerformed(evt);
            }
        });
        add(AddOrganizationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageInventorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageInventorybtnActionPerformed
 for (Network network : system.getNetworkList()) {
            
           for (Enterprise enterpris : network.getEnterpriseDirectory().getEnterpriseList())  {             
              if(enterpris.getEnterpriseType().equals(Pharmacy))   {
                 
                  for (Organization organization : enterpris.getOrganizationDirectory().getOrganizationList()) {
                   if(organization instanceof PharmacyAdminOrganization)    {
                     
                        Adminorganization = (PharmacyAdminOrganization) organization;
                      // System.out.println("hello"+Adminorganization);
                        break;
                   }
                  }
                         break;
              }
           }
           break;
        }
        SupplierDirectory supplierDirectory=Adminorganization.getSuppDirectory();
        ManageDrug msi = new ManageDrug(userProcessContainer, supplierDirectory);
    userProcessContainer.add("ManageDrug", msi);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);        
    }//GEN-LAST:event_ManageInventorybtnActionPerformed

    private void ManageSupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupplierbtnActionPerformed
        // TODO add your handling code here:
        for (Network network : system.getNetworkList()) {
            
           for (Enterprise enterpris : network.getEnterpriseDirectory().getEnterpriseList())  {             
              if(enterpris.getEnterpriseType().equals(Pharmacy))   {
                 
                  for (Organization organization : enterpris.getOrganizationDirectory().getOrganizationList()) {
                   if(organization instanceof PharmacyAdminOrganization)    {
                     
                        Adminorganization = (PharmacyAdminOrganization) organization;
                      // System.out.println("hello"+Adminorganization);
                        break;
                   }
                  }
                         break;
              }
           }
           break;
        }
        SupplierDirectory supplierDirectory=Adminorganization.getSuppDirectory();
        ManageSupplier ms = new ManageSupplier(userProcessContainer, supplierDirectory);
        userProcessContainer.add("ManageSupplier", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageSupplierbtnActionPerformed

    private void AddOrganizationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrganizationBtnActionPerformed
        // TODO add your handling code here:
        AddOrganization addOrganization = new AddOrganization(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("AddOrganization", addOrganization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AddOrganizationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrganizationBtn;
    private javax.swing.JButton ManageInventorybtn;
    private javax.swing.JButton ManageSupplierbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
