/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBankAdministrativeRole;

import Business.Donor.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivam
 */
public class ManageDonor extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private String result;
   private ArrayList<Donor>accepted;
   private ArrayList<Donor>Rejected;
   private Donor donor;
    /**
     * Creates new form ManageDonor
     */
    public ManageDonor(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.userAccount = account;
         this.enterprise = enterprise;
         accepted=new ArrayList<>();
         Rejected=new ArrayList<>();
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
            if(org instanceof DonorOrganization)
                organization = (DonorOrganization)org;
        
            
        populateRequestTable();
    }
    public void populateRequestTable(){
       
        DefaultTableModel model = (DefaultTableModel) AdminJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[2];
            donor=(Donor) ((LabTestWorkRequest) request).getDonor();
            row[0] = donor;
            result = ((LabTestWorkRequest) request).getTestResult();
            row[1] = result == null ? "Waiting" : result;         
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AdminJTable = new javax.swing.JTable();
        AcceptedDonorbtn = new javax.swing.JButton();
        RejectedDonorbtn = new javax.swing.JButton();

        AdminJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Donor Name", "Test Result"
            }
        ));
        jScrollPane1.setViewportView(AdminJTable);

        AcceptedDonorbtn.setText("Accept");
        AcceptedDonorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptedDonorbtnActionPerformed(evt);
            }
        });

        RejectedDonorbtn.setText("Reject");
        RejectedDonorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectedDonorbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AcceptedDonorbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RejectedDonorbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RejectedDonorbtn)
                    .addComponent(AcceptedDonorbtn))
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RejectedDonorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectedDonorbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = AdminJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        //LabTestWorkRequest request = (LabTestWorkRequest)AdminJTable.getValueAt(selectedRow, 0);
        Donor d = (Donor)AdminJTable.getValueAt(selectedRow, 0);
        
         Rejected.add(d);
            
    }//GEN-LAST:event_RejectedDonorbtnActionPerformed

    private void AcceptedDonorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptedDonorbtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = AdminJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        Donor d = (Donor)AdminJTable.getValueAt(selectedRow, 0);
        
        accepted.add(d);
        JOptionPane.showMessageDialog(null, "Added the Donor to the list", "Info", JOptionPane.INFORMATION_MESSAGE);
            
     
    }//GEN-LAST:event_AcceptedDonorbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptedDonorbtn;
    private javax.swing.JTable AdminJTable;
    private javax.swing.JButton RejectedDonorbtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
