/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBankLabAssisstantRole;

import Business.Donor.Donor;
import Business.DonorSensor.VitalSign;
import Business.DonorSensor.VitalSignDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class DonorSensorVitalSign extends javax.swing.JPanel {
JPanel userProcessContainer;
private Donor donor;
private Enterprise enterprise;
private VitalSignDirectory vitalSignHistory;
//private UserAccount account;
private VitalSign vitalsign;
String time;
    /**
     * Creates new form PatientSensorVitalSign
     */
    public DonorSensorVitalSign(JPanel userProcessContainer,Enterprise enterprise,Donor donor) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.donor=donor;
         //this.account = account;
         Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        vitalSignHistory=donor.getVitalSignDir();
        RandomVitalSign();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        HemaglobinTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        OrgantypeComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        BloodGroupTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AntigenAComboBox = new javax.swing.JComboBox();
        AntigenBComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BodySizeText = new javax.swing.JTextField();
        BloodPressureText = new javax.swing.JTextField();
        BloodPlatletsField = new javax.swing.JTextField();
        AntigenDQComboBox = new javax.swing.JComboBox();
        AntigenDB1ComboBox = new javax.swing.JComboBox();
        AntigenCComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        TimeStampText = new javax.swing.JTextField();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel3.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 528, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 528, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel17.setText("Donor Vital Sign");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, -1, -1));
        jPanel3.add(HemaglobinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 382, 116, -1));

        jLabel19.setText("Organ Type");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, -1, -1));

        OrgantypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lungs", "Kindney", "Heart", "Liver", "Pancreas", " " }));
        jPanel3.add(OrgantypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 88, -1, -1));

        jLabel11.setText("Blood Group");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, -1, -1));
        jPanel3.add(BloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 121, 111, 20));

        jLabel9.setText("Marker A Antigen");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, -1, -1));

        AntigenAComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        AntigenAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntigenAComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(AntigenAComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 151, 119, -1));

        AntigenBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel3.add(AntigenBComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 184, 119, -1));

        jLabel8.setText("Marker B Antigen");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 188, -1, -1));

        jLabel7.setText("Marker C Antigen");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 225, 168, -1));

        jLabel6.setText("Marker DB1 Antigen");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, -1, 25));

        jLabel5.setText("Marker DQ Antigen");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, -1, -1));

        jLabel3.setText("Blood Platlets");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 317, -1, -1));

        jLabel15.setText("Blood Pressure");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 351, -1, 20));

        jLabel4.setText("Hemaglobin level");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 389, -1, -1));

        jLabel14.setText("Body Mass");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 423, -1, -1));
        jPanel3.add(BodySizeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 414, 116, -1));
        jPanel3.add(BloodPressureText, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 350, 116, -1));

        BloodPlatletsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPlatletsFieldActionPerformed(evt);
            }
        });
        jPanel3.add(BloodPlatletsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 318, 116, -1));

        AntigenDQComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel3.add(AntigenDQComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 290, 116, -1));

        AntigenDB1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel3.add(AntigenDB1ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 254, 116, -1));

        AntigenCComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel3.add(AntigenCComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 221, 116, -1));

        jLabel2.setText("TimeStamp");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 451, -1, -1));
        jPanel3.add(TimeStampText, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 446, 116, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void RandomVitalSign()
    { Random rn = new Random();
        BloodPlatletsField.setText(String.valueOf(rn.nextFloat()*(140-70) + 70));
        BloodPressureText.setText(String.valueOf(rn.nextFloat()*(130-80) + 80));
        HemaglobinTextField.setText(String.valueOf(rn.nextFloat()*(120-70) + 70));
    }
    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        Timestamp timeStamp = new Timestamp(new Date().getTime());
        time = String.valueOf(timeStamp);
        TimeStampText.setText(String.valueOf(time));
        VitalSign vitalsign=vitalSignHistory.addvitalsign();
      

        vitalsign.setAntigenA(Integer.parseInt(AntigenAComboBox.getSelectedItem().toString()));
        vitalsign.setAntigenB(Integer.parseInt(AntigenBComboBox.getSelectedItem().toString()));
        vitalsign.setAntigenC(Integer.parseInt(AntigenCComboBox.getSelectedItem().toString()));
        vitalsign.setAntigenDB1(Integer.parseInt(AntigenDB1ComboBox.getSelectedItem().toString()));
        vitalsign.setAntigenDQ(Integer.parseInt(AntigenDQComboBox.getSelectedItem().toString()));
        vitalsign.setBloodType(BloodGroupTextField.getText());
        vitalsign.setBloodPlatlets(BloodPlatletsField.getText());
        vitalsign.setBloodPressure(BloodPressureText.getText());
        vitalsign.setBodySize(Integer.parseInt(BodySizeText.getText()));
        vitalsign.setHemoglobinLevel(HemaglobinTextField.getText());
        vitalsign.setBloodType(BloodGroupTextField.getText());
        vitalsign.setOrganType(OrgantypeComboBox.getSelectedItem().toString());
        vitalsign.setTimestamp(time);
//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof DonorOrganization){
//                org = organization;
//
//                break;
//            }
//        }
//        if (org!=null){
//            System.out.println("DONOR ORG");
//            org.getWorkQueue().getWorkRequestList().add(request);
//            userAccount.getWorkQueue().getWorkRequestList().add(request);
//
//        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void AntigenAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntigenAComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntigenAComboBoxActionPerformed

    private void BloodPlatletsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPlatletsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPlatletsFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AntigenAComboBox;
    private javax.swing.JComboBox AntigenBComboBox;
    private javax.swing.JComboBox AntigenCComboBox;
    private javax.swing.JComboBox AntigenDB1ComboBox;
    private javax.swing.JComboBox AntigenDQComboBox;
    private javax.swing.JTextField BloodGroupTextField;
    private javax.swing.JTextField BloodPlatletsField;
    private javax.swing.JTextField BloodPressureText;
    private javax.swing.JTextField BodySizeText;
    private javax.swing.JTextField HemaglobinTextField;
    private javax.swing.JComboBox OrgantypeComboBox;
    private javax.swing.JTextField TimeStampText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
