/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganBankLabAssisstantRole;

import Business.Donor.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
private UserAccount userAccount;
   LabTestWorkRequest request;
   private Donor donor;
   private Enterprise enterprise;
   private LabAssistantQueueJPanel labAssistantQueueJPanell;
    /**
     * Creates new form LabTestWorkRequest
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, LabTestWorkRequest request,Donor donor,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
    this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.donor=donor;
        this.enterprise= enterprise;
        this.userAccount=userAccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HepatitisBComboBox = new javax.swing.JComboBox();
        HIVComboBox = new javax.swing.JComboBox();
        HepatitisCComboBox = new javax.swing.JComboBox();
        SyphilisComboBox = new javax.swing.JComboBox();
        CytomegalovirusComboVirus = new javax.swing.JComboBox();
        EpsteinComboBox = new javax.swing.JComboBox();
        ResultComboBox = new javax.swing.JComboBox();
        VitalSignButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 359, -1, -1));

        jLabel1.setText("Result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 280, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 359, -1, -1));

        jLabel2.setText("Human Immunodeficiency Virus");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 34, -1, -1));

        jLabel3.setText("Hepatitis B");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 75, -1, -1));

        jLabel4.setText("Syphilis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 154, -1, -1));

        jLabel5.setText("Hepatitis C");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 109, -1, -1));

        jLabel7.setText("Epstein Barr Virus");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 234, -1, -1));

        jLabel8.setText("Cytomegalovirus");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 193, -1, -1));

        HepatitisBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        HepatitisBComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HepatitisBComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(HepatitisBComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 71, -1, -1));

        HIVComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        HIVComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIVComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(HIVComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 30, -1, -1));

        HepatitisCComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        jPanel1.add(HepatitisCComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 105, -1, -1));

        SyphilisComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        jPanel1.add(SyphilisComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 150, -1, -1));

        CytomegalovirusComboVirus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        jPanel1.add(CytomegalovirusComboVirus, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 189, -1, -1));

        EpsteinComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Positive", "Negative" }));
        jPanel1.add(EpsteinComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 231, -1, -1));

        ResultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pass", "Fail" }));
        ResultComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ResultComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 276, 111, -1));

        VitalSignButton.setText("Add Vital Sign");
        VitalSignButton.setEnabled(false);
        VitalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalSignButtonActionPerformed(evt);
            }
        });
        jPanel1.add(VitalSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Donor Lab Test ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel6)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6)
                .addContainerGap(431, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(126, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(ResultComboBox.getSelectedItem().toString().equals("Pass"))
        { VitalSignButton.setEnabled(true);
        request.setTestResult(ResultComboBox.getSelectedItem().toString());
        request.setStatus("Pending");
        request.setDonor(donor);
        //System.out.println(donor);
        
        donor.getLabtest().setHIV(HIVComboBox.getSelectedItem().toString());
        donor.getLabtest().setHBV(HepatitisBComboBox.getSelectedItem().toString());
        donor.getLabtest().setHCV(HepatitisCComboBox.getSelectedItem().toString());
        donor.getLabtest().setSyphilis(SyphilisComboBox.getSelectedItem().toString());
        donor.getLabtest().setCMV(CytomegalovirusComboVirus.getSelectedItem().toString());
        donor.getLabtest().setEMV(EpsteinComboBox.getSelectedItem().toString());
       
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DonorOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        }
      else
      { 
          JOptionPane.showMessageDialog(null, "Patient is not suitable for Donation!!", "Info", JOptionPane.INFORMATION_MESSAGE);
      }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
      
        //LabAssistantQueueJPanel dwjp = (LabAssistantQueueJPanel) component;
       // dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        labAssistantQueueJPanell.populateTable();
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void HepatitisBComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HepatitisBComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HepatitisBComboBoxActionPerformed

    private void HIVComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIVComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIVComboBoxActionPerformed

    private void ResultComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultComboBoxActionPerformed

    private void VitalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalSignButtonActionPerformed
        
         
        AddVitalSign addVitalSign = new AddVitalSign(userProcessContainer, request,(Donor)request.getDonor(),enterprise,userAccount);
        userProcessContainer.add("AddVitalSign", addVitalSign);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

      
    }//GEN-LAST:event_VitalSignButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CytomegalovirusComboVirus;
    private javax.swing.JComboBox EpsteinComboBox;
    private javax.swing.JComboBox HIVComboBox;
    private javax.swing.JComboBox HepatitisBComboBox;
    private javax.swing.JComboBox HepatitisCComboBox;
    private javax.swing.JComboBox ResultComboBox;
    private javax.swing.JComboBox SyphilisComboBox;
    private javax.swing.JButton VitalSignButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
