/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;


import Business.Donor.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.Person.Person;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class PatientRegistrationForm extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PatientOrganization org;
    /**
     * Creates new form DonarRegistrationForm
     */
    public PatientRegistrationForm(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
       // this.directory = directory;
        this.enterprise = enterprise;
        
        for (Organization orga : this.enterprise.getOrganizationDirectory().getOrganizationList()){
            if (orga instanceof PatientOrganization){
                org = (PatientOrganization)orga;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PatientNameTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AddPatient = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TownTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ZipTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AreaTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Patient Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 44, -1, -1));

        jLabel3.setText("Patient Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 158, -1, -1));

        PatientNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PatientNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 153, 143, -1));

        jButton1.setText(">> Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 498, 81, -1));

        AddPatient.setText("Submit Information");
        AddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(AddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 498, -1, -1));

        jLabel4.setText("Date of birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 185, -1, -1));
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 185, 143, -1));

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 233, -1, -1));

        jLabel6.setText("Street Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 258, -1, 26));
        jPanel1.add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 258, 140, -1));

        jLabel7.setText("Town");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 295, -1, -1));
        jPanel1.add(TownTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 290, 140, -1));

        jLabel8.setText("Zip");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 322, -1, -1));

        ZipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ZipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 322, 140, -1));

        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 360, 140, -1));

        jLabel11.setText("Area Code");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 402, -1, -1));
        jPanel1.add(AreaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 392, 140, -1));

        jLabel12.setText("Phone Number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 429, -1, -1));
        jPanel1.add(PhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 424, 140, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 229, -1, -1));

        buttonGroup1.add(Male);
        Male.setText("Male");
        jPanel1.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 229, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientActionPerformed
        // TODO add your handling code here:
        Patient p = new Patient();
            Date date = jDateChooser.getDate();
        if(PatientNameTextField.getText().trim().isEmpty())   {
           JOptionPane.showMessageDialog(this, "Enter First Name", "Error", JOptionPane.OK_OPTION);
           }
        else if(!PatientNameTextField.getText().matches("[a-zA-Z]*"))   {
       JOptionPane.showMessageDialog(this, "Not a valid Name ", "Error", JOptionPane.OK_OPTION);
       }
       else if (buttonGroup1.isSelected(null))
{
  JOptionPane.showMessageDialog(this, "Please Select the gender", "Error", JOptionPane.OK_OPTION);
}
       // Date date = jDateChooser.getDate();
        else if (date == null) {
      JOptionPane.showMessageDialog(null, "Date is required.");
    }
  

         else if(AddressTextField.getText().trim().isEmpty())   {
           JOptionPane.showMessageDialog(this, "Enter Address", "Error", JOptionPane.OK_OPTION);
          }
         else if(ZipTextField.getText().trim().isEmpty())   {
           JOptionPane.showMessageDialog(this, "Enter Zip Code ", "Error", JOptionPane.OK_OPTION);
           
          }
       else if(!ZipTextField.getText().matches("\\d{5}"))   {
           JOptionPane.showMessageDialog(this, "Enter Valid Zip Code  ", "Error", JOptionPane.OK_OPTION);
       }
       else if(!EmailTextField.getText().matches("^[A-Za-z0-9.%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,4}$"))
              {JOptionPane.showMessageDialog(this, " Enter valid Email ID!", "Error", JOptionPane.OK_OPTION);
              }
      else if(AreaTextField.getText().trim().isEmpty())   {
           JOptionPane.showMessageDialog(this, "Enter Area ", "Error", JOptionPane.OK_OPTION);
           
          }
      else if ( !AreaTextField.getText().matches("\\d{3}")){
        JOptionPane.showMessageDialog(this, "Enter Valid Area Code ", "Error", JOptionPane.OK_OPTION); 
        }
       
       if(PhoneTextField.getText().trim().isEmpty() )  {
           JOptionPane.showMessageDialog(this, "Enter Phone Number ", "Error", JOptionPane.OK_OPTION);  
          }
       if ( !PhoneTextField.getText().matches("\\d{10}")){
           JOptionPane.showMessageDialog(this, "Enter Valid Phone Number ", "Error", JOptionPane.OK_OPTION); 
       }
        else{
        p.setName(PatientNameTextField.getText());
        if(Male.isSelected())
          {
              p.setGender("Male");
          }
        else if(female.isSelected())
        {
            p.setGender("Female");
        }
        //System.out.println(Male.isSelected());
        p.setAddress(AddressTextField.getText());
        p.setArea(AreaTextField.getText());
    
        String strDate = DateFormat.getDateInstance().format(date);
        p.setDob(strDate);
        
        System.out.println(strDate);
        p.setEmail(EmailTextField.getText());
        p.setZip(ZipTextField.getText());
        p.setTown(TownTextField.getText());
        p.setPhone(PhoneTextField.getText());
        org.getPersonDirectory().getPersonList().add(p);
        
//        for(Person patient : org.getPersonDirectory().getPersonList())  {
//            //Patient pa = (Patient)patient; 
//            System.out.println(patient.getName());
//        }
       JOptionPane.showMessageDialog(null, "Patient added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AddPatientActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //receptionistQueueJPanel.DonorComboBox();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ZipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PatientNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatient;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField AreaTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField PatientNameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextField TownTextField;
    private javax.swing.JTextField ZipTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
