/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Donor.Donor;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.OrganBankAdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    /**
     * Creates new form ReceptionistWorkAreaJPanel
     */
    public ReceptionistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Organization organization, Enterprise enterprise,EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
       this.organization=organization;
       this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddPatientBtn = new javax.swing.JButton();
        RequestTestBtn = new javax.swing.JButton();
        AmbulanceRequest = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ReceptionistRole/sb10069454y-001.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        AddPatientBtn.setText("Add Patient");
        AddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtnActionPerformed(evt);
            }
        });
        add(AddPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 389, 160, -1));

        RequestTestBtn.setText("Request Lab Test");
        RequestTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestTestBtnActionPerformed(evt);
            }
        });
        add(RequestTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 448, 170, -1));

        AmbulanceRequest.setText("Emergency");
        AmbulanceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulanceRequestActionPerformed(evt);
            }
        });
        add(AmbulanceRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtnActionPerformed
        // TODO add your handling code here:
        PatientRegistrationForm patientRegistrationForm = new PatientRegistrationForm(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", patientRegistrationForm);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AddPatientBtnActionPerformed

    private void RequestTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestTestBtnActionPerformed
        // TODO add your handling code here:
         UserInterface.ReceptionistRole.ReceptionistQueueJPanel rqjp = new UserInterface.ReceptionistRole.ReceptionistQueueJPanel(userProcessContainer,userAccount,organization,enterprise,system);
        userProcessContainer.add("ReceptionistQueueJPanel", rqjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_RequestTestBtnActionPerformed

    private void AmbulanceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulanceRequestActionPerformed
        // TODO add your handling code here:
        AmbulanceRequestJPanel ambulanceRequestJPanel = new AmbulanceRequestJPanel(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("AmbulanceRequestJPanel", ambulanceRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_AmbulanceRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientBtn;
    private javax.swing.JButton AmbulanceRequest;
    private javax.swing.JButton RequestTestBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
