/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.NurseRole.PatientList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
private EcoSystem business;
private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization,Enterprise enterprise,EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.organization = organization;
        this.enterprise=enterprise;
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaitingButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ProcessRequestButton = new javax.swing.JButton();
        MedicineHistory = new javax.swing.JButton();
        AmbulanceBtn = new javax.swing.JButton();
        ViewDonorReport1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WaitingButton.setText("Wating List");
        WaitingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitingButtonActionPerformed(evt);
            }
        });
        add(WaitingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 212, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/industry-doctors.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 240));

        ProcessRequestButton.setText("Process Donation");
        ProcessRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessRequestButtonActionPerformed(evt);
            }
        });
        add(ProcessRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 212, -1));

        MedicineHistory.setText("View Medicine History");
        MedicineHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineHistoryActionPerformed(evt);
            }
        });
        add(MedicineHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 212, -1));

        AmbulanceBtn.setText("Emergency");
        AmbulanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulanceBtnActionPerformed(evt);
            }
        });
        add(AmbulanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 212, -1));

        ViewDonorReport1.setText("View Donor Report");
        ViewDonorReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDonorReport1ActionPerformed(evt);
            }
        });
        add(ViewDonorReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 212, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void WaitingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitingButtonActionPerformed
        // TODO add your handling code here:
        DoctorWorkQueueJPanel doctorWorkQueueJPanel = new DoctorWorkQueueJPanel(userProcessContainer,userAccount,organization,enterprise,business);
        userProcessContainer.add("DoctorWorkQueueJPanel", doctorWorkQueueJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_WaitingButtonActionPerformed

    private void ProcessRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessRequestButtonActionPerformed
        // TODO add your handling code here:
        PatientSummaryJPanel patientSummaryJPanel = new PatientSummaryJPanel(userProcessContainer,userAccount,enterprise,business);
        userProcessContainer.add("PatientSummaryJPanel", patientSummaryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ProcessRequestButtonActionPerformed

    private void MedicineHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineHistoryActionPerformed
        // TODO add your handling code here:
         Patientlist patientlist = new Patientlist(userProcessContainer ,enterprise);
        userProcessContainer.add("PatientList", patientlist);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MedicineHistoryActionPerformed

    private void AmbulanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulanceBtnActionPerformed
        // TODO add your handling code here:
        AmbulanceRequestJPanel ambulanceRequestJPanel = new AmbulanceRequestJPanel(userProcessContainer ,userAccount,organization,enterprise);
        userProcessContainer.add("AmbulanceRequestJPanel", ambulanceRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AmbulanceBtnActionPerformed

    private void ViewDonorReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDonorReport1ActionPerformed
        // TODO add your handling code here:
        DonorList donorlist = new DonorList(userProcessContainer ,enterprise,business);
        userProcessContainer.add("Donorlist", donorlist);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewDonorReport1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmbulanceBtn;
    private javax.swing.JButton MedicineHistory;
    private javax.swing.JButton ProcessRequestButton;
    private javax.swing.JButton ViewDonorReport1;
    private javax.swing.JButton WaitingButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
