/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.PatientSensor.Test;
import Business.PatientSensor.TestDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.NurseRole.ProcessRequestJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivam
 */
public class PatientSummaryJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private Patient patient;
   private EcoSystem business;
   private TestDirectory vitalSignHistory;
    
    /**
     * Creates new form SelectMatchingPatientJPanel
     */
    public PatientSummaryJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
         this.userAccount = account;
         this.enterprise = enterprise;
         this.business=business;
         
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
            if(org instanceof PatientOrganization)
                organization = (PatientOrganization)org;
        
        
        populateRequestTable();
    }
    public void populateRequestTable(){
       
        DefaultTableModel model = (DefaultTableModel) PatientJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[2];
            
            
            patient=(Patient) ((LabTestWorkRequest) request).getPatient();
            System.out.println(patient);
            row[0] = patient;
            String result = ((LabTestWorkRequest) request).getTestResult();
            row[1] = result == null ? "Waiting" : result;         
            model.addRow(row);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientJTable = new javax.swing.JTable();
        ViewButton = new javax.swing.JButton();
        ProcessDonationBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        OrgantypeComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        BloodGroupTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AntigenAComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        AntigenBComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        AntigenCComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        AntigenDB1ComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        AntigenDQComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        BloodPlatletsField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BloodPressureText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HemaglobinTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BodySizeText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Patient Profile Summary");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(PatientJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 15, 518, 132));

        ViewButton.setText("View");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 159, -1, -1));

        ProcessDonationBtn.setText("Process donation");
        ProcessDonationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessDonationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ProcessDonationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 573, 140, -1));

        jLabel17.setText("Organ Type");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, -1, -1));

        jPanel1.add(OrgantypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 214, 111, -1));

        jLabel11.setText("Blood Group");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 247, -1, -1));
        jPanel1.add(BloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 247, 111, 20));

        jLabel9.setText("Marker A Antigen");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, -1, -1));

        AntigenAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntigenAComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(AntigenAComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 279, 111, -1));

        jLabel8.setText("Marker B Antigen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 312, -1, -1));

        jPanel1.add(AntigenBComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 312, 111, -1));

        jLabel7.setText("Marker C Antigen");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 349, 168, -1));

        jPanel1.add(AntigenCComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 345, 111, -1));

        jLabel6.setText("Marker DB1 Antigen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 378, -1, 25));

        jPanel1.add(AntigenDB1ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 378, 111, -1));

        jLabel5.setText("Marker DQ Antigen");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 411, -1, -1));

        jPanel1.add(AntigenDQComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 411, 111, -1));

        jLabel3.setText("Blood Platlets");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 438, -1, -1));

        BloodPlatletsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPlatletsFieldActionPerformed(evt);
            }
        });
        jPanel1.add(BloodPlatletsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 439, 111, -1));

        jLabel15.setText("Blood Pressure");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 472, -1, 20));
        jPanel1.add(BloodPressureText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 471, 111, -1));

        jLabel4.setText("Hemaglobin level");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 509, -1, -1));
        jPanel1.add(HemaglobinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 503, 111, -1));

        jLabel14.setText("Body Mass");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 543, -1, -1));
        jPanel1.add(BodySizeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 535, 111, -1));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 565, -1, -1));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = PatientJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        String value= (String)PatientJTable.getValueAt(selectedRow, 1);
        
        if(value.equals("Complete"))
        {
            Patient p = (Patient)PatientJTable.getValueAt(selectedRow, 0);
        vitalSignHistory=p.getTestDir();
         int size = vitalSignHistory.getTestdir().size();
        Test test =vitalSignHistory.getTestdir().get(size - 1);
            System.out.println("Patient " + patient.getName());
        System.out.println("Size " + test);
        System.out.println(vitalSignHistory.getTestdir().get(size - 1));
        System.out.println("Blood Presuure " + test.getBloodPressure());
        
       BloodPressureText.setText(test.getBloodPressure());
        AntigenAComboBox.addItem(String.valueOf(test.getAntigenA()));
        AntigenBComboBox.addItem(String.valueOf(test.getAntigenB()));
        AntigenCComboBox.addItem(String.valueOf(test.getAntigenC()));
        AntigenDB1ComboBox.addItem(String.valueOf(test.getAntigenDB1()));
        AntigenDQComboBox.addItem(String.valueOf(test.getAntigenDQ()));
        OrgantypeComboBox.addItem(String.valueOf(test.getOrganType()));
        BloodGroupTextField.setText(String.valueOf(test.getBloodType()));
        HemaglobinTextField.setText(String.valueOf(test.getHemoglobinLevel()));
        BloodPlatletsField.setText(String.valueOf(test.getBloodPlatlets()));
        BodySizeText.setText(String.valueOf(test.getBodyWeight()));

        
        }
        else{
            JOptionPane.showMessageDialog(this,"Pateint Test Request is Incomplete Cannot view the Vital sign!","information",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void ProcessDonationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessDonationBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = PatientJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        String value= (String)PatientJTable.getValueAt(selectedRow, 1);
        
        if(value.equals("Complete"))
        {
            Patient p = (Patient)PatientJTable.getValueAt(selectedRow, 0);
        SelectMatchingPatientJPanel selectMatchingPatientJPanel = new SelectMatchingPatientJPanel(userProcessContainer,enterprise,business,p);
        userProcessContainer.add("ProcessRequestJPanel", selectMatchingPatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);}
        else
        {JOptionPane.showMessageDialog(this,"Pateint Test Request is Incomplete cannot allow further Process!","information",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ProcessDonationBtnActionPerformed

    private void AntigenAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntigenAComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntigenAComboBoxActionPerformed

    private void BloodPlatletsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPlatletsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPlatletsFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AntigenAComboBox;
    private javax.swing.JComboBox AntigenBComboBox;
    private javax.swing.JComboBox AntigenCComboBox;
    private javax.swing.JComboBox AntigenDB1ComboBox;
    private javax.swing.JComboBox AntigenDQComboBox;
    private javax.swing.JTextField BloodGroupTextField;
    private javax.swing.JTextField BloodPlatletsField;
    private javax.swing.JTextField BloodPressureText;
    private javax.swing.JTextField BodySizeText;
    private javax.swing.JTextField HemaglobinTextField;
    private javax.swing.JComboBox OrgantypeComboBox;
    private javax.swing.JTable PatientJTable;
    private javax.swing.JButton ProcessDonationBtn;
    private javax.swing.JButton ViewButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
