/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;
import java.awt.CardLayout;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivam
 */

public class SendEmail extends javax.swing.JPanel {
private JPanel userProcessContainer;
    /**
     * Creates new form SendEmail
     */
    public SendEmail(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SendMailBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EmailPasswordField = new javax.swing.JPasswordField();
        PatientMailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SendMailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DoctorRole/download.jpeg"))); // NOI18N
        SendMailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMailBtnActionPerformed(evt);
            }
        });
        add(SendMailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 100, 100));

        jLabel1.setText("Doctor Email Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 111, -1, -1));

        jLabel2.setText("Enter Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 159, -1, -1));

        jLabel3.setText("Patient Email Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 214, -1, -1));
        add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 101, 174, -1));
        add(EmailPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 159, 174, -1));
        add(PatientMailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 214, 174, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Send Mail");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 34, -1, -1));

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SendMailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMailBtnActionPerformed
        // TODO add your handling code here:
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactor.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        Session session=Session.getDefaultInstance(props,
         new javax.mail.Authenticator() {
             protected PasswordAuthentication getPasswordAuthentication(){
             //return new PasswordAuthentication("northeastern1989@gmail.com", "abcxyz1989");
                 char[] passwordCharArray = EmailPasswordField.getPassword();
        String password = String.valueOf(passwordCharArray);
             return new PasswordAuthentication(EmailTextField.getText(), password );
             }
         
}        );
        
        try{
            Message message= new MimeMessage(session);
            message.setFrom( new InternetAddress(EmailTextField.getText()));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(PatientMailTextField.getText()));
            message.setSubject("Hi Donor is Avaliable");
            message.setText("Please reply with confirmation");
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Email Sent");
        }
        
        catch(Exception e)
        
        {JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SendMailBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code her
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField EmailPasswordField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField PatientMailTextField;
    private javax.swing.JButton SendMailBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
